- name: IPA Server Backup
  hosts: all
  become: true

  tasks:
  - name: Find Old IPA Backups To Remove
    find:
      paths: {{ ipa_backups_path }}/ipa*
      age: {{ ipa_backup_remove_days | default(8) }}d 
      file_type: directory
      depth: 1
    register: ipa_backups_to_delete

  - name: Delete Old IPA Backups
    file:
       path: {{ item.path }}
       state: absent
    with_items: {{ ipa_backups_to_delete }}

    find {{ freeipa_server_backup_path }}/ipa* -maxdepth 1 -type d -mtime +{{ freeipa_server_backup_max_age | default(14) }} -exec rm -rf {} \;
  - name: Full IPA Backup on {{ ansible_fqdn }}
    shell: /sbin/ipa-backup
    register: ipa_backup_results

  - name: IPA Backup Results
    debug:
      var: ipa_backup_results.stdout_lines

  - name: Sync Backup To AWS Storage
    shell: /usr/local/aws/bin/aws s3 sync {{ ipa_backups_path }} s3://idm-master-backup/$today
    register: aws_results

  - name: AWS Sync Results
    debug:
      var: aws_results.stdout_lines

  - name: Check IPA Status
    shell: ipactl status
    register: ipactl_results

  - name: Status of IPA 
    debug:
      var: ipactl_results.stdout_lines
